"""change_created_3

Revision ID: 3a53744b2c44
Revises: 191622f457c2
Create Date: 2023-05-28 10:40:11.040113+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a53744b2c44'
down_revision = '191622f457c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outstanding_tokens', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('outstanding_tokens', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outstanding_tokens', 'updated_at')
    op.drop_column('outstanding_tokens', 'created_at')
    # ### end Alembic commands ###
